#!/usr/bin/pythonw

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

even_sum = 0                # Counter
n1 = 1                      # First number in Fib sequence
n2 = 2                      # Second number in Fib sequence
while n2 <= 4 * 1000000:    # While the most recent term does not exceed 4 mil,
    if n2 % 2 == 0:         # If the most recent term is even,
        even_sum += n2      # Add the value of the term to the bank
    n = n1 + n2             # Find next term in the sequence
    n1 = n2
    n2 = n
print even_sum